version: '3'

services:
  hello-world:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DB_CONNECTION_STRING: mongodb://db/nest
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    volumes: 
      - /data:/data/db
    ports:
      - 27017:27017

